USE Cancerbioinfo;

LOAD DATA LOCAL INFILE 'new_data/genes.csv' 
INTO TABLE Gene 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'new_data/proteins.csv' 
INTO TABLE Protein 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'new_data/domains.csv' 
INTO TABLE Domaine 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;